# Generated by Django 5.2.11 on 2026-02-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = []
# This migration previously added fields like `is_staff` and `is_superuser`, and set up the `groups` ManyToMany relationship. Those schema changes are already reflected in 0001_initial, so leave this migration empty to prevent missing-column or duplicate operations when creating a fresh database for development or tests.