# Generated by Django 5.2.11 on 2026-02-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_groups_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = []

# This migration previously removed the `name` field and altered `is_staff` to be a BooleanField. Since the `name` field was never added in 0001_initial, and `is_staff` is already a BooleanField in 0001_initial, we can leave this migration empty to prevent missing-column or duplicate operations when creating a fresh database for development or tests.