# Generated by Django 5.2.11 on 2026-02-26 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseproposal',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseproposal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_histories', to='purchases.purchaseproposal'),
        ),
        migrations.AddField(
            model_name='purchaseproposalitem',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseproposal'),
        ),
        migrations.AddIndex(
            model_name='purchaseproposal',
            index=models.Index(fields=['status'], name='purchases_p_status_cae8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseproposal',
            index=models.Index(fields=['created_at'], name='purchases_p_created_ceb9df_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseproposal',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='purchaseproposal_total_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='purchasehistory',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='purchase_total_cost_non_negative'),
        ),
    ]
