# Generated by Django 5.2.11 on 2026-03-28 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_histories', to='purchases.purchaseproposal'),
        ),
        migrations.AlterField(
            model_name='purchaseproposalitem',
            name='proposal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseproposal'),
            preserve_default=False,
        ),
    ]
