# Generated by Django 5.2.11 on 2026-02-22 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='purchasehistory',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_purchased__gte', 0)), name='purchase_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='purchasehistory',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='purchase_total_cost_non_negative'),
        ),
        migrations.AddField(
            model_name='purchaseproposal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='purchaseproposal',
            index=models.Index(fields=['status'], name='purchases_p_status_cae8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseproposal',
            index=models.Index(fields=['created_at'], name='purchases_p_created_ceb9df_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseproposal',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='purchaseproposal_total_cost_non_negative'),
        ),
    ]
