# Generated by Django 5.2.11 on 2026-02-25 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseproposal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseProposalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('ware_house_name', models.CharField(blank=True, max_length=255, null=True)),
                ('proposed_quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='purchasehistory',
            name='purchase_quantity_non_negative',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='drug_name',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='purchase_at',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='quantity_purchased',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='strength',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_histories', to='purchases.purchaseproposal'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseproposal',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='purchaseproposalitem',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseproposal'),
        ),
    ]
