# Generated by Django 5.2.11 on 2026-02-20 22:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('availability', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('review_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
