# Generated by Django 5.2.11 on 2026-02-26 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_house_name', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence_score', models.FloatField()),
                ('review_required', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='files.file')),
            ],
        ),
        migrations.CreateModel(
            name='OCRResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_product_name', models.CharField(max_length=255)),
                ('extracted_strength', models.CharField(blank=True, max_length=100, null=True)),
                ('extracted_company', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_quantity', models.PositiveIntegerField()),
                ('extracted_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ocr_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ai_integration.ocrresults')),
            ],
        ),
        migrations.AddIndex(
            model_name='ocrresults',
            index=models.Index(fields=['ware_house_name'], name='ai_integrat_ware_ho_e61ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresults',
            index=models.Index(fields=['file'], name='ai_integrat_file_id_e2330a_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresults',
            index=models.Index(fields=['created_at'], name='ai_integrat_created_320b86_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresults',
            index=models.Index(fields=['review_required'], name='ai_integrat_review__723d44_idx'),
        ),
        migrations.AddConstraint(
            model_name='ocrresults',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 1)), name='ocr_confidence_range'),
        ),
    ]
