# Generated by Django 5.2.11 on 2026-02-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['drug_name'], name='ai_integrat_drug_na_a77ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['company'], name='ai_integrat_company_0e696b_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['created_at'], name='ai_integrat_created_6fe5da_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['review_required'], name='ai_integrat_review__9e1a90_idx'),
        ),
        migrations.AddConstraint(
            model_name='ocrresult',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='ocr_confidence_range'),
        ),
    ]
