# Generated by Django 5.2.11 on 2026-03-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0002_ocrjob'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ocrjob',
            index=models.Index(fields=['status'], name='ai_integrat_status_86d197_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrjob',
            index=models.Index(fields=['created_at'], name='ai_integrat_created_4857fa_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrjob',
            index=models.Index(fields=['updated_at'], name='ai_integrat_updated_312fa1_idx'),
        ),
    ]
