# Generated by Django 5.2.11 on 2026-03-01 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0003_ocrjob_ai_integrat_status_86d197_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrjob',
            name='job_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ocrresults',
            name='job_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_results', to='ai_integration.ocrjob'),
        ),
        migrations.AlterField(
            model_name='ocrjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=50),
        ),
    ]
