# Generated by Django 5.2.11 on 2026-02-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0003_ocrresultitem_ocrresults_delete_ocrresult_and_more'),
        ('files', '0003_file_ware_house_name_alter_file_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ocrresults',
            name='ocr_confidence_range',
        ),
        migrations.AddConstraint(
            model_name='ocrresults',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 1)), name='ocr_confidence_range'),
        ),
    ]
