# Generated by Django 5.2.11 on 2026-03-01 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0004_ocrjob_job_id_ocrresults_job_id_alter_ocrjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrjob',
            name='job_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
