# Generated by Django 5.2.11 on 2026-03-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0005_alter_ocrjob_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocrresults',
            old_name='job_id',
            new_name='job',
        ),
    ]
