# Generated by Django 5.2.11 on 2026-03-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0006_rename_job_id_ocrresults_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=50),
        ),
    ]
