# Generated by Django 5.2.11 on 2026-03-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0007_alter_ocrjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('ocr_done', 'OCR Done'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=50),
        ),
    ]
