# Generated by Django 5.2.11 on 2026-03-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0008_alter_ocrjob_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrresultitem',
            name='extracted_quantity',
        ),
        migrations.RemoveField(
            model_name='ocrresultitem',
            name='extracted_strength',
        ),
    ]
