# Generated by Django 5.2.11 on 2026-03-28 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0009_remove_ocrresultitem_extracted_quantity_and_more'),
        ('files', '0002_alter_file_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OCRResults',
            new_name='OCRResult',
        ),
        migrations.AlterModelTable(
            name='ocrresult',
            table='ai_integration_ocrresults',
        ),
    ]
