# Generated by Django 5.2.11 on 2026-03-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=255)),
                ('quantity_on_hand', models.IntegerField()),
                ('min_threshold', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['product_name'], name='inventory_i_product_9f1b40_idx'), models.Index(fields=['strength'], name='inventory_i_strengt_cbb1e1_idx'), models.Index(fields=['quantity_on_hand'], name='inventory_i_quantit_be6a58_idx'), models.Index(fields=['min_threshold'], name='inventory_i_min_thr_ce7df6_idx'), models.Index(fields=['updated_at'], name='inventory_i_updated_22da79_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='quantity_non_negative')],
            },
        ),
    ]
