# Generated by Django 5.2.11 on 2026-02-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['drug_name'], name='inventory_i_drug_na_00a58f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['strength'], name='inventory_i_strengt_cbb1e1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['quantity_on_hand'], name='inventory_i_quantit_be6a58_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['min_threshold'], name='inventory_i_min_thr_ce7df6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['updated_at'], name='inventory_i_updated_22da79_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='quantity_non_negative'),
        ),
    ]
