# Generated by Django 5.2.11 on 2026-02-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_inventory_i_drug_na_00a58f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventory',
            name='inventory_i_drug_na_00a58f_idx',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='drug_name',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product_name'], name='inventory_i_product_9f1b40_idx'),
        ),
    ]
