# Generated by Django 5.2.11 on 2026-03-28 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_hardening_constraints'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventory',
            name='inventory_i_quantit_be6a58_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='inventory_i_min_thr_ce7df6_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='inventory_i_updated_22da79_idx',
        ),
    ]
