# Generated by Django 5.2.11 on 2026-05-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0003_remove_inventory_inventory_i_quantit_be6a58_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                ("status", models.CharField(choices=[("completed", "Completed"), ("refunded", "Refunded")], default="completed", max_length=20)),
                ("discount_percentage", models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cashier", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transactions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "pos_transactions",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_method", models.CharField(choices=[("cash", "Cash"), ("card", "Card"), ("insurance", "Insurance")], max_length=20)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=12)),
                ("transaction", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="pos.transaction")),
            ],
            options={
                "db_table": "pos_payments",
            },
        ),
        migrations.CreateModel(
            name="TransactionItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount_percentage", models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("inventory_item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transaction_items", to="inventory.inventory")),
                ("transaction", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="pos.transaction")),
            ],
            options={
                "db_table": "pos_transaction_items",
            },
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["receipt_number"], name="pos_transac_receip_1bb02d_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["created_at"], name="pos_transac_created_2d6b22_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["cashier"], name="pos_transac_cashier_2f28d9_idx"),
        ),
        migrations.AddIndex(
            model_name="transactionitem",
            index=models.Index(fields=["transaction"], name="pos_transac_transac_b6fd20_idx"),
        ),
        migrations.AddIndex(
            model_name="transactionitem",
            index=models.Index(fields=["inventory_item"], name="pos_transac_invento_356fc3_idx"),
        ),
    ]
