# Generated by Django 5.2.11 on 2026-05-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='pos_transac_receipt_bd58b4_idx',
            old_name='pos_transac_receip_1bb02d_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='pos_transac_created_d5b5bb_idx',
            old_name='pos_transac_created_2d6b22_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='pos_transac_cashier_48d3cf_idx',
            old_name='pos_transac_cashier_2f28d9_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionitem',
            new_name='pos_transac_transac_f6efe5_idx',
            old_name='pos_transac_transac_b6fd20_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionitem',
            new_name='pos_transac_invento_6955f1_idx',
            old_name='pos_transac_invento_356fc3_idx',
        ),
    ]
