# Generated by Django 5.2.11 on 2026-03-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('proposal_approved', 'Proposal Approved'), ('proposal_rejected', 'Proposal Rejected'), ('inventory_adjusted', 'Inventory Adjusted'), ('capital_changed', 'Capital Changed'), ('assign_role', 'Assign Role'), ('revoke_role', 'Revoke Role'), ('create_permission', 'Create Permission'), ('delete_permission', 'Delete Permission')], max_length=64)),
                ('entity_object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('entity_repr', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique permission code (e.g., create_user, view_inventory)', max_length=100, unique=True, verbose_name='codename')),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete')], default='read', max_length=20, verbose_name='action')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'db_table': 'rbac_permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_system', models.BooleanField(default=False, help_text='System roles cannot be deleted', verbose_name='system role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'rbac_roles',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rbac_role_permissions',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
            ],
            options={
                'verbose_name': 'user role',
                'verbose_name_plural': 'user roles',
                'db_table': 'rbac_user_roles',
            },
        ),
    ]
