# Generated by Django 5.2.11 on 2026-02-27 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rbac', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('proposal_approved', 'Proposal Approved'), ('proposal_rejected', 'Proposal Rejected'), ('inventory_adjusted', 'Inventory Adjusted'), ('capital_changed', 'Capital Changed'), ('assign_role', 'Assign Role'), ('revoke_role', 'Revoke Role'), ('create_permission', 'Create Permission'), ('delete_permission', 'Delete Permission')], max_length=64)),
                ('entity_object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('entity_repr', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('entity_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['action', 'created_at'], name='rbac_auditl_action_02e0b2_idx'), models.Index(fields=['actor', 'created_at'], name='rbac_auditl_actor_i_c39d6b_idx'), models.Index(fields=['entity_content_type', 'entity_object_id'], name='rbac_auditl_entity__77d8fe_idx')],
            },
        ),
    ]
