# Generated by Django 5.2.11 on 2026-03-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('proposal_approved', 'Proposal Approved'), ('proposal_rejected', 'Proposal Rejected'), ('inventory_adjusted', 'Inventory Adjusted'), ('capital_changed', 'Capital Changed'), ('assign_role', 'Assign Role'), ('revoke_role', 'Revoke Role'), ('create_permission', 'Create Permission'), ('delete_permission', 'Delete Permission'), ('user_registered', 'User Registered'), ('admin_created', 'Admin Created'), ('password_changed', 'Password Changed'), ('file_uploaded', 'File Uploaded'), ('ocr_manual_dispatch', 'OCR Manual Dispatch')], max_length=64),
        ),
    ]
