# Generated by Django 5.2.11 on 2026-02-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=255, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('ware_house_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['s3_key'], name='files_file_s3_key_de8f02_idx'), models.Index(fields=['status'], name='files_file_status_0bd07b_idx'), models.Index(fields=['created_at'], name='files_file_created_22ed95_idx')],
            },
        ),
    ]
