# Generated by Django 5.2.11 on 2026-02-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['status'], name='files_file_status_0bd07b_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['created_at'], name='files_file_created_22ed95_idx'),
        ),
    ]
