# Generated by Django 5.2.11 on 2026-02-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_files_file_status_0bd07b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ware_house_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['s3_key'], name='files_file_s3_key_de8f02_idx'),
        ),
    ]
