# Generated by Django 5.2.11 on 2026-02-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['type'], name='notificatio_type_63e928_idx'),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['created_at'], name='notificatio_created_4e77da_idx'),
        ),
    ]
