# Generated by Django 5.2.11 on 2026-03-27 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_usernotification_delivery'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='notificatio_user_id_319bc5_idx',
            old_name='notificatio_user_id_6a6c79_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='notificatio_notific_693d0a_idx',
            old_name='notificatio_notifi_e7f4cf_idx',
        ),
    ]
