# Generated by Django 5.2.11 on 2026-03-28 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_notificatio_user_id_6a6c79_idx_notificatio_user_id_319bc5_idx_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications_notifications',
        ),
    ]
