# Generated by Django 5.2.11 on 2026-02-20 22:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=255)),
                ('quantity_sold', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_at', models.DateTimeField()),
            ],
        ),
    ]
