# Generated by Django 5.2.11 on 2026-03-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=255)),
                ('quantity_sold', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['product_name'], name='sales_sale_product_929a84_idx'), models.Index(fields=['sold_at'], name='sales_sale_sold_at_607748_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_sold__gte', 0)), name='sale_quantity_non_negative'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sale_unit_price_non_negative')],
            },
        ),
    ]
