# Generated by Django 5.2.11 on 2026-02-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['drug_name'], name='sales_sale_drug_na_bb041c_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sold_at'], name='sales_sale_sold_at_607748_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_sold__gte', 0)), name='sale_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sale_unit_price_non_negative'),
        ),
    ]
