# Generated by Django 5.2.11 on 2026-02-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_sales_sale_drug_na_bb041c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale_drug_na_bb041c_idx',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='drug_name',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['product_name'], name='sales_sale_product_929a84_idx'),
        ),
    ]
